source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGPlusButtonsViewDemo'

target 'LGPlusButtonsViewDemo' do
    pod 'LGPlusButtonsView', :path => '../'
    pod 'LGDrawer', '~> 1.0.0'
end
